### ISSUE TITLE
Add section for modern Windows administration

### ISSUE THREAD

**Issue by unixorn** [unixorn/sysadmin-reading-list#14]
This list is *nix-centric, mainly because I've spent most of my career herding the various Unix flavors. The reality of life though is that most people still have to deal with at least a little bit of Windows, and the list could use some links to Windows automation resources too.

**Comment by darnold76** [comment]
I will have at this one.

**Comment by unixorn** [comment]
Thanks!

**Comment by darnold76** [comment]
#21 has started a Windows Administration section.  I will work to add links to this section throughout the week and as I can.   Most of my admin experience is on the UNIX/Linux side and I am learning Windows Administration so as I learn, I will contribute.
