### ISSUE TITLE
Add Python section

### ISSUE THREAD

**Issue by unixorn** [unixorn/sysadmin-reading-list#2]
Add more items to the Python section. Specifically, articles or blog posts that show how to use Python to manage your systems, good Python tools, that sort of thing.

**Comment by EmilLuta** [comment]
Hello there!

Do you think you could provide extra information? I can see there is already a Python Section (a rather small one).

**Comment by unixorn** [comment]
Added, sorry for the vagueness in the original issue.

**Comment by EmilLuta** [comment]
Onto it.

**Comment by EmilLuta** [comment]
6101efd23b98242633ce555f1515da7dc56c4922
