### ISSUE TITLE
Add Docker section

### ISSUE THREAD

**Issue by unixorn** [unixorn/sysadmin-reading-list#40]
At the very least, talk about getting Docker set up so you can test on your own machine, have sections for Mac, Windows and Linux hosts.

There should also be a list of tutorials/references for Kubernetes, CoreOS, Rancher, ECS and whatever else someone wants to add.

**Comment by mkasberg** [comment]
I'm pretty familiar with Docker; I can at least get the basics for this in place.

I'll put something together over the weekend.
